//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.7.0-dev
// 	protoc               v3.21.12
// source: internal/host/kubernetes/kubernetes.proto

package kubernetes

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

type proxy struct{}

func NewProxy() Proxy {
	return proxy{}
}

//go:wasm-module kubernetes
//export get
//go:linkname _get
func _get(ptr uint32, size uint32) uint64

func (h proxy) Get(ctx context.Context, request *GetRequest) (*GetReply, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _get(ptr, size)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(GetReply)
	if err = response.UnmarshalVT(buf); err != nil {
		return nil, err
	}
	return response, nil
}
