name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        uses: dmvolod/mage-action@v2.3.1
        with:
          version: latest
          args: lint
      - name: Install TinyGo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.27.0
          install-binaryen: false
      - name: Generate WASM files
        uses: dmvolod/mage-action@v2.3.1
        with:
          version: latest
          args: generate
      - name: Test
        uses: dmvolod/mage-action@v2.3.1
        with:
          version: latest
          args: test
